// Copyright 2017 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package codeu.model.data;

import java.time.Instant;
import java.util.UUID;

/** Class representing a Notification. Notifications are generated by the system. */
public class Notification {

  private final UUID id;
  private final UUID message;
  private final UUID conversation;
  private final UUID mentionedUser;
  private final Instant creation;

  /**
   * Constructs a new Notification.
   *
   * @param id the ID of this Notification
   * @param message the ID of the Message with the mention
   * @param conversation the ID of the Conversation with the mention
   * @param mentionedUser the ID of the User who was mentioned
   * @param creation the creation time of this Notification
   */
  public Notification(UUID id, UUID message, UUID conversation, UUID mentionedUser, Instant creation) {
    this.id = id;
    this.message = message;
    this.conversation = conversation;
    this.mentionedUser = mentionedUser;
    this.creation = creation;
  }

  /** Returns the ID of this Notification. */
  public UUID getId() {
    return id;
  }

  /** Returns the ID of the Message with the mention. */
  public UUID getMessageId() {
    return message;
  }

  /** Returns the ID of the Conversation with the mention. */
  public UUID getConversationId() {
    return conversation;
  }

  /** Returns the ID of the mentioned User. */
  public UUID getMentionedUserId() {
    return mentionedUser;
  }

  /** Returns the creation time of this Notification. */
  public Instant getCreationTime() {
    return creation;
  }

}